// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/Components/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport: require('./StandardImport')
});
require('./Pages');
require('./Partials');
require('./Widgets');