// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/Components/Partials/index.js

(module.exports = require('./namespace'))

.addModules({
  Board:          require('./Board'),
  NumberBar:      require('./NumberBar'),
  StandardImport: require('./StandardImport')
});