// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/Models/index.js

(module.exports = require('./namespace'))

.addModules({
  CurrentGame: require('./CurrentGame'),
  GameView:    require('./GameView')
});