// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/index.js

(module.exports = require('./namespace'))

.addModules({
  App:            require('./App'),
  Main:           require('./Main'),
  StandardImport: require('./StandardImport'),
  Style:          require('./Style')
});
require('./Components');
require('./Models');