// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Sodoku.Quest',
  (class Quest extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Components/namespace');
require('./Models/namespace');