// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/Components/Widgets/index.js

(module.exports = require('./namespace'))

.addModules({
  Cell:         require('./Cell'),
  NumberButton: require('./NumberButton')
});