// generated by Neptune Namespaces v4.x.x
// file: tests/Sodoku.Quest/namespace.js

module.exports = require('../namespace').addNamespace(
  'Sodoku.Quest',
  (class Quest extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
