// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/Components/Pages/index.js

(module.exports = require('./namespace'))

.addModules({
  Game:           require('./Game'),
  StandardImport: require('./StandardImport')
});