// generated by Neptune Namespaces v4.x.x
// file: Sodoku.Quest/Components/Pages/namespace.js

module.exports = require('../namespace').addNamespace(
  'Pages',
  class Pages extends Neptune.PackageNamespace {}
);
